### GET ALL BOOKINGS
GET http://localhost:8080/booking


### POST A LIST OF BOOKINGS
POST http://localhost:8080/booking
Content-Type: application/json

[
  {
    "clientName": "Jonathan",
    "clientPhone": "0345130557",
    "clientEmail": "jo@gmail.com",
    "roomNumber": 8,
    "roomDescription": "Double Room",
    "date": "2025-03-12"
  }
]